<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGn4pYVn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGn4pYVn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGn4pYVn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGn4pYVn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGn4pYVn\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gn4pYVn',
    'container.build_id' => 'f18faec5',
    'container.build_time' => 1620303302,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGn4pYVn');
